// flow-typed signature: 8a6a3ab2b9884abde65b591b84e6ff93
// flow-typed version: <<STUB>>/nwb_v0.18.x/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nwb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nwb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nwb/express' {
  declare module.exports: any;
}

declare module 'nwb/lib/appCommands' {
  declare module.exports: any;
}

declare module 'nwb/lib/bin/nwb' {
  declare module.exports: any;
}

declare module 'nwb/lib/cli' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/build-demo' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/build-inferno-app' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/build-inferno' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/build-preact-app' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/build-preact' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/build-react-app' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/build-react-component' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/build-react' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/build-web-app' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/build-web-module' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/build-web' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/build' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/check-config' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/clean-app' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/clean-demo' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/clean-module' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/clean' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/inferno' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/init' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/new' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/preact' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/react' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/serve-inferno-app' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/serve-inferno' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/serve-preact-app' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/serve-preact' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/serve-react-app' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/serve-react-demo' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/serve-react' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/serve-web-app' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/serve-web' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/serve' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/test-inferno' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/test-preact' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/test-react' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/test' {
  declare module.exports: any;
}

declare module 'nwb/lib/commands/web' {
  declare module.exports: any;
}

declare module 'nwb/lib/constants' {
  declare module.exports: any;
}

declare module 'nwb/lib/createBabelConfig' {
  declare module.exports: any;
}

declare module 'nwb/lib/createKarmaConfig' {
  declare module.exports: any;
}

declare module 'nwb/lib/createProject' {
  declare module.exports: any;
}

declare module 'nwb/lib/createServerWebpackConfig' {
  declare module.exports: any;
}

declare module 'nwb/lib/createWebpackConfig' {
  declare module.exports: any;
}

declare module 'nwb/lib/debug' {
  declare module.exports: any;
}

declare module 'nwb/lib/devServer' {
  declare module.exports: any;
}

declare module 'nwb/lib/errors' {
  declare module.exports: any;
}

declare module 'nwb/lib/expressMiddleware' {
  declare module.exports: any;
}

declare module 'nwb/lib/getPluginConfig' {
  declare module.exports: any;
}

declare module 'nwb/lib/getUserConfig' {
  declare module.exports: any;
}

declare module 'nwb/lib/inferno/index' {
  declare module.exports: any;
}

declare module 'nwb/lib/inferno/inferno-preset' {
  declare module.exports: any;
}

declare module 'nwb/lib/inferno/renderShim' {
  declare module.exports: any;
}

declare module 'nwb/lib/karmaServer' {
  declare module.exports: any;
}

declare module 'nwb/lib/moduleBuild' {
  declare module.exports: any;
}

declare module 'nwb/lib/preact/index' {
  declare module.exports: any;
}

declare module 'nwb/lib/preact/preact-preset' {
  declare module.exports: any;
}

declare module 'nwb/lib/preact/renderShim' {
  declare module.exports: any;
}

declare module 'nwb/lib/quickCommands' {
  declare module.exports: any;
}

declare module 'nwb/lib/react/index' {
  declare module.exports: any;
}

declare module 'nwb/lib/react/react-dev-preset' {
  declare module.exports: any;
}

declare module 'nwb/lib/react/react-hmre-preset' {
  declare module.exports: any;
}

declare module 'nwb/lib/react/renderShim' {
  declare module.exports: any;
}

declare module 'nwb/lib/types' {
  declare module.exports: any;
}

declare module 'nwb/lib/utils' {
  declare module.exports: any;
}

declare module 'nwb/lib/web/index' {
  declare module.exports: any;
}

declare module 'nwb/lib/webpackBuild' {
  declare module.exports: any;
}

declare module 'nwb/lib/webpackServer' {
  declare module.exports: any;
}

declare module 'nwb/lib/WebpackStatusPlugin' {
  declare module.exports: any;
}

declare module 'nwb/lib/webpackUtils' {
  declare module.exports: any;
}

declare module 'nwb/polyfills' {
  declare module.exports: any;
}

declare module 'nwb/templates/inferno-app/nwb.config' {
  declare module.exports: any;
}

declare module 'nwb/templates/inferno-app/src/App' {
  declare module.exports: any;
}

declare module 'nwb/templates/inferno-app/src/index' {
  declare module.exports: any;
}

declare module 'nwb/templates/inferno-app/tests/App-test' {
  declare module.exports: any;
}

declare module 'nwb/templates/preact-app/nwb.config' {
  declare module.exports: any;
}

declare module 'nwb/templates/preact-app/src/App' {
  declare module.exports: any;
}

declare module 'nwb/templates/preact-app/src/index' {
  declare module.exports: any;
}

declare module 'nwb/templates/preact-app/tests/App-test' {
  declare module.exports: any;
}

declare module 'nwb/templates/react-app/nwb.config' {
  declare module.exports: any;
}

declare module 'nwb/templates/react-app/src/App' {
  declare module.exports: any;
}

declare module 'nwb/templates/react-app/src/index' {
  declare module.exports: any;
}

declare module 'nwb/templates/react-app/tests/App-test' {
  declare module.exports: any;
}

declare module 'nwb/templates/react-component/demo/src/index' {
  declare module.exports: any;
}

declare module 'nwb/templates/react-component/nwb.config' {
  declare module.exports: any;
}

declare module 'nwb/templates/react-component/src/index' {
  declare module.exports: any;
}

declare module 'nwb/templates/react-component/tests/index-test' {
  declare module.exports: any;
}

declare module 'nwb/templates/web-app/nwb.config' {
  declare module.exports: any;
}

declare module 'nwb/templates/web-app/src/index' {
  declare module.exports: any;
}

declare module 'nwb/templates/web-app/tests/index-test' {
  declare module.exports: any;
}

declare module 'nwb/templates/web-module/nwb.config' {
  declare module.exports: any;
}

declare module 'nwb/templates/web-module/src/index' {
  declare module.exports: any;
}

declare module 'nwb/templates/web-module/tests/index-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nwb/express.js' {
  declare module.exports: $Exports<'nwb/express'>;
}
declare module 'nwb/lib/appCommands.js' {
  declare module.exports: $Exports<'nwb/lib/appCommands'>;
}
declare module 'nwb/lib/bin/nwb.js' {
  declare module.exports: $Exports<'nwb/lib/bin/nwb'>;
}
declare module 'nwb/lib/cli.js' {
  declare module.exports: $Exports<'nwb/lib/cli'>;
}
declare module 'nwb/lib/commands/build-demo.js' {
  declare module.exports: $Exports<'nwb/lib/commands/build-demo'>;
}
declare module 'nwb/lib/commands/build-inferno-app.js' {
  declare module.exports: $Exports<'nwb/lib/commands/build-inferno-app'>;
}
declare module 'nwb/lib/commands/build-inferno.js' {
  declare module.exports: $Exports<'nwb/lib/commands/build-inferno'>;
}
declare module 'nwb/lib/commands/build-preact-app.js' {
  declare module.exports: $Exports<'nwb/lib/commands/build-preact-app'>;
}
declare module 'nwb/lib/commands/build-preact.js' {
  declare module.exports: $Exports<'nwb/lib/commands/build-preact'>;
}
declare module 'nwb/lib/commands/build-react-app.js' {
  declare module.exports: $Exports<'nwb/lib/commands/build-react-app'>;
}
declare module 'nwb/lib/commands/build-react-component.js' {
  declare module.exports: $Exports<'nwb/lib/commands/build-react-component'>;
}
declare module 'nwb/lib/commands/build-react.js' {
  declare module.exports: $Exports<'nwb/lib/commands/build-react'>;
}
declare module 'nwb/lib/commands/build-web-app.js' {
  declare module.exports: $Exports<'nwb/lib/commands/build-web-app'>;
}
declare module 'nwb/lib/commands/build-web-module.js' {
  declare module.exports: $Exports<'nwb/lib/commands/build-web-module'>;
}
declare module 'nwb/lib/commands/build-web.js' {
  declare module.exports: $Exports<'nwb/lib/commands/build-web'>;
}
declare module 'nwb/lib/commands/build.js' {
  declare module.exports: $Exports<'nwb/lib/commands/build'>;
}
declare module 'nwb/lib/commands/check-config.js' {
  declare module.exports: $Exports<'nwb/lib/commands/check-config'>;
}
declare module 'nwb/lib/commands/clean-app.js' {
  declare module.exports: $Exports<'nwb/lib/commands/clean-app'>;
}
declare module 'nwb/lib/commands/clean-demo.js' {
  declare module.exports: $Exports<'nwb/lib/commands/clean-demo'>;
}
declare module 'nwb/lib/commands/clean-module.js' {
  declare module.exports: $Exports<'nwb/lib/commands/clean-module'>;
}
declare module 'nwb/lib/commands/clean.js' {
  declare module.exports: $Exports<'nwb/lib/commands/clean'>;
}
declare module 'nwb/lib/commands/inferno.js' {
  declare module.exports: $Exports<'nwb/lib/commands/inferno'>;
}
declare module 'nwb/lib/commands/init.js' {
  declare module.exports: $Exports<'nwb/lib/commands/init'>;
}
declare module 'nwb/lib/commands/new.js' {
  declare module.exports: $Exports<'nwb/lib/commands/new'>;
}
declare module 'nwb/lib/commands/preact.js' {
  declare module.exports: $Exports<'nwb/lib/commands/preact'>;
}
declare module 'nwb/lib/commands/react.js' {
  declare module.exports: $Exports<'nwb/lib/commands/react'>;
}
declare module 'nwb/lib/commands/serve-inferno-app.js' {
  declare module.exports: $Exports<'nwb/lib/commands/serve-inferno-app'>;
}
declare module 'nwb/lib/commands/serve-inferno.js' {
  declare module.exports: $Exports<'nwb/lib/commands/serve-inferno'>;
}
declare module 'nwb/lib/commands/serve-preact-app.js' {
  declare module.exports: $Exports<'nwb/lib/commands/serve-preact-app'>;
}
declare module 'nwb/lib/commands/serve-preact.js' {
  declare module.exports: $Exports<'nwb/lib/commands/serve-preact'>;
}
declare module 'nwb/lib/commands/serve-react-app.js' {
  declare module.exports: $Exports<'nwb/lib/commands/serve-react-app'>;
}
declare module 'nwb/lib/commands/serve-react-demo.js' {
  declare module.exports: $Exports<'nwb/lib/commands/serve-react-demo'>;
}
declare module 'nwb/lib/commands/serve-react.js' {
  declare module.exports: $Exports<'nwb/lib/commands/serve-react'>;
}
declare module 'nwb/lib/commands/serve-web-app.js' {
  declare module.exports: $Exports<'nwb/lib/commands/serve-web-app'>;
}
declare module 'nwb/lib/commands/serve-web.js' {
  declare module.exports: $Exports<'nwb/lib/commands/serve-web'>;
}
declare module 'nwb/lib/commands/serve.js' {
  declare module.exports: $Exports<'nwb/lib/commands/serve'>;
}
declare module 'nwb/lib/commands/test-inferno.js' {
  declare module.exports: $Exports<'nwb/lib/commands/test-inferno'>;
}
declare module 'nwb/lib/commands/test-preact.js' {
  declare module.exports: $Exports<'nwb/lib/commands/test-preact'>;
}
declare module 'nwb/lib/commands/test-react.js' {
  declare module.exports: $Exports<'nwb/lib/commands/test-react'>;
}
declare module 'nwb/lib/commands/test.js' {
  declare module.exports: $Exports<'nwb/lib/commands/test'>;
}
declare module 'nwb/lib/commands/web.js' {
  declare module.exports: $Exports<'nwb/lib/commands/web'>;
}
declare module 'nwb/lib/constants.js' {
  declare module.exports: $Exports<'nwb/lib/constants'>;
}
declare module 'nwb/lib/createBabelConfig.js' {
  declare module.exports: $Exports<'nwb/lib/createBabelConfig'>;
}
declare module 'nwb/lib/createKarmaConfig.js' {
  declare module.exports: $Exports<'nwb/lib/createKarmaConfig'>;
}
declare module 'nwb/lib/createProject.js' {
  declare module.exports: $Exports<'nwb/lib/createProject'>;
}
declare module 'nwb/lib/createServerWebpackConfig.js' {
  declare module.exports: $Exports<'nwb/lib/createServerWebpackConfig'>;
}
declare module 'nwb/lib/createWebpackConfig.js' {
  declare module.exports: $Exports<'nwb/lib/createWebpackConfig'>;
}
declare module 'nwb/lib/debug.js' {
  declare module.exports: $Exports<'nwb/lib/debug'>;
}
declare module 'nwb/lib/devServer.js' {
  declare module.exports: $Exports<'nwb/lib/devServer'>;
}
declare module 'nwb/lib/errors.js' {
  declare module.exports: $Exports<'nwb/lib/errors'>;
}
declare module 'nwb/lib/expressMiddleware.js' {
  declare module.exports: $Exports<'nwb/lib/expressMiddleware'>;
}
declare module 'nwb/lib/getPluginConfig.js' {
  declare module.exports: $Exports<'nwb/lib/getPluginConfig'>;
}
declare module 'nwb/lib/getUserConfig.js' {
  declare module.exports: $Exports<'nwb/lib/getUserConfig'>;
}
declare module 'nwb/lib/inferno/index.js' {
  declare module.exports: $Exports<'nwb/lib/inferno/index'>;
}
declare module 'nwb/lib/inferno/inferno-preset.js' {
  declare module.exports: $Exports<'nwb/lib/inferno/inferno-preset'>;
}
declare module 'nwb/lib/inferno/renderShim.js' {
  declare module.exports: $Exports<'nwb/lib/inferno/renderShim'>;
}
declare module 'nwb/lib/karmaServer.js' {
  declare module.exports: $Exports<'nwb/lib/karmaServer'>;
}
declare module 'nwb/lib/moduleBuild.js' {
  declare module.exports: $Exports<'nwb/lib/moduleBuild'>;
}
declare module 'nwb/lib/preact/index.js' {
  declare module.exports: $Exports<'nwb/lib/preact/index'>;
}
declare module 'nwb/lib/preact/preact-preset.js' {
  declare module.exports: $Exports<'nwb/lib/preact/preact-preset'>;
}
declare module 'nwb/lib/preact/renderShim.js' {
  declare module.exports: $Exports<'nwb/lib/preact/renderShim'>;
}
declare module 'nwb/lib/quickCommands.js' {
  declare module.exports: $Exports<'nwb/lib/quickCommands'>;
}
declare module 'nwb/lib/react/index.js' {
  declare module.exports: $Exports<'nwb/lib/react/index'>;
}
declare module 'nwb/lib/react/react-dev-preset.js' {
  declare module.exports: $Exports<'nwb/lib/react/react-dev-preset'>;
}
declare module 'nwb/lib/react/react-hmre-preset.js' {
  declare module.exports: $Exports<'nwb/lib/react/react-hmre-preset'>;
}
declare module 'nwb/lib/react/renderShim.js' {
  declare module.exports: $Exports<'nwb/lib/react/renderShim'>;
}
declare module 'nwb/lib/types.js' {
  declare module.exports: $Exports<'nwb/lib/types'>;
}
declare module 'nwb/lib/utils.js' {
  declare module.exports: $Exports<'nwb/lib/utils'>;
}
declare module 'nwb/lib/web/index.js' {
  declare module.exports: $Exports<'nwb/lib/web/index'>;
}
declare module 'nwb/lib/webpackBuild.js' {
  declare module.exports: $Exports<'nwb/lib/webpackBuild'>;
}
declare module 'nwb/lib/webpackServer.js' {
  declare module.exports: $Exports<'nwb/lib/webpackServer'>;
}
declare module 'nwb/lib/WebpackStatusPlugin.js' {
  declare module.exports: $Exports<'nwb/lib/WebpackStatusPlugin'>;
}
declare module 'nwb/lib/webpackUtils.js' {
  declare module.exports: $Exports<'nwb/lib/webpackUtils'>;
}
declare module 'nwb/polyfills.js' {
  declare module.exports: $Exports<'nwb/polyfills'>;
}
declare module 'nwb/templates/inferno-app/nwb.config.js' {
  declare module.exports: $Exports<'nwb/templates/inferno-app/nwb.config'>;
}
declare module 'nwb/templates/inferno-app/src/App.js' {
  declare module.exports: $Exports<'nwb/templates/inferno-app/src/App'>;
}
declare module 'nwb/templates/inferno-app/src/index.js' {
  declare module.exports: $Exports<'nwb/templates/inferno-app/src/index'>;
}
declare module 'nwb/templates/inferno-app/tests/App-test.js' {
  declare module.exports: $Exports<'nwb/templates/inferno-app/tests/App-test'>;
}
declare module 'nwb/templates/preact-app/nwb.config.js' {
  declare module.exports: $Exports<'nwb/templates/preact-app/nwb.config'>;
}
declare module 'nwb/templates/preact-app/src/App.js' {
  declare module.exports: $Exports<'nwb/templates/preact-app/src/App'>;
}
declare module 'nwb/templates/preact-app/src/index.js' {
  declare module.exports: $Exports<'nwb/templates/preact-app/src/index'>;
}
declare module 'nwb/templates/preact-app/tests/App-test.js' {
  declare module.exports: $Exports<'nwb/templates/preact-app/tests/App-test'>;
}
declare module 'nwb/templates/react-app/nwb.config.js' {
  declare module.exports: $Exports<'nwb/templates/react-app/nwb.config'>;
}
declare module 'nwb/templates/react-app/src/App.js' {
  declare module.exports: $Exports<'nwb/templates/react-app/src/App'>;
}
declare module 'nwb/templates/react-app/src/index.js' {
  declare module.exports: $Exports<'nwb/templates/react-app/src/index'>;
}
declare module 'nwb/templates/react-app/tests/App-test.js' {
  declare module.exports: $Exports<'nwb/templates/react-app/tests/App-test'>;
}
declare module 'nwb/templates/react-component/demo/src/index.js' {
  declare module.exports: $Exports<'nwb/templates/react-component/demo/src/index'>;
}
declare module 'nwb/templates/react-component/nwb.config.js' {
  declare module.exports: $Exports<'nwb/templates/react-component/nwb.config'>;
}
declare module 'nwb/templates/react-component/src/index.js' {
  declare module.exports: $Exports<'nwb/templates/react-component/src/index'>;
}
declare module 'nwb/templates/react-component/tests/index-test.js' {
  declare module.exports: $Exports<'nwb/templates/react-component/tests/index-test'>;
}
declare module 'nwb/templates/web-app/nwb.config.js' {
  declare module.exports: $Exports<'nwb/templates/web-app/nwb.config'>;
}
declare module 'nwb/templates/web-app/src/index.js' {
  declare module.exports: $Exports<'nwb/templates/web-app/src/index'>;
}
declare module 'nwb/templates/web-app/tests/index-test.js' {
  declare module.exports: $Exports<'nwb/templates/web-app/tests/index-test'>;
}
declare module 'nwb/templates/web-module/nwb.config.js' {
  declare module.exports: $Exports<'nwb/templates/web-module/nwb.config'>;
}
declare module 'nwb/templates/web-module/src/index.js' {
  declare module.exports: $Exports<'nwb/templates/web-module/src/index'>;
}
declare module 'nwb/templates/web-module/tests/index-test.js' {
  declare module.exports: $Exports<'nwb/templates/web-module/tests/index-test'>;
}
